[package]
name = "bonbon"
version = "0.4.2"
edition = "2021"
repository = "https://github.com/ItsLimeNade/bonbon"
homepage = "https://github.com/ItsLimeNade/bonbon?tab=readme-ov-file"
authors = ["Limenade"]
description = "A sweet and simple Rust library for generating static diabetes data visualizations."
readme = "./README.md"
license = "MPL-2.0"
keywords = ["diabetes", "chart", "plot"]
categories = ["data-structures", "science::bioinformatics", "multimedia::images", "rendering::data-formats", "visualization"]

[dependencies]
ab_glyph = "0.2.32"
chrono = {version = "0.4.43",features = ["serde"]}
chrono-tz = {version = "0.10.4", features = ["serde"]}
image = {version = "0.25.9", features = ["serde"]}
imageproc = "0.26.0"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
thiserror = "2.0.17"
cinnamon = {version = "1.0.1", optional = true}
rayon = "1.11.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
cinnamon = "1.0.1"


[features]
default = []
cinnamon = ["dep:cinnamon"]
beetroot = [] # contextual stickers on the glucose graph and bg card

[[example]]
name = "stickers"
required-features = ["beetroot"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
